//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobTab()
        {
            this.Application_Tab = new HashSet<Application_Tab>();
        }
    
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string Job_Title { get; set; }
        public int No_Vacancies { get; set; }
        public int Salary { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Tab> Application_Tab { get; set; }
        public virtual CompanyReg CompanyReg { get; set; }
    }
}
